export const COURSE_CREATE_REQUEST = "COURSE_CREATE_REQUEST"
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS"
export const COURSE_CREATE_FAIL = "COURSE_CREATE_FAIL"

export const COURSE_EDIT_REQUEST = "COURSE_EDIT_REQUEST"
export const COURSE_EDIT_SUCCESS = "COURSE_EDIT_SUCCESS"
export const COURSE_EDIT_FAIL = "COURSE_EDIT_FAIL"
export const COURSE_EDIT_RESET = "COURSE_EDIT_RESET"

export const COURSES_VIEW_REQUEST = "COURSES_VIEW_REQUEST"
export const COURSES_VIEW_SUCCESS = "COURSES_VIEW_SUCCESS"
export const COURSES_VIEW_FAIL = "COURSES_VIEW_FAIL"
export const COURSES_VIEW_RESET = "COURSES_VIEW_RESET"

export const COURSES_PRICE_VIEW_REQUEST = "COURSES_PRICE_VIEW_REQUEST"
export const COURSES_PRICE_VIEW_SUCCESS = "COURSES_PRICE_VIEW_SUCCESS"
export const COURSES_PRICE_VIEW_FAIL = "COURSES_PRICE_VIEW_FAIL"
export const COURSES_PRICE_VIEW_RESET = "COURSES_PRICE_VIEW_RESET"

export const COURSE_VIEW_REQUEST = "COURSE_VIEW_REQUEST"
export const COURSE_VIEW_SUCCESS = "COURSE_VIEW_SUCCESS"
export const COURSE_VIEW_FAIL = "COURSE_VIEW_FAIL"
export const COURSE_VIEW_RESET = "COURSE_VIEW_RESET"

export const TOPIC_CREATE_REQUEST = "TOPIC_CREATE_REQUEST"
export const TOPIC_CREATE_SUCCESS = "TOPIC_CREATE_SUCCESS"
export const TOPIC_CREATE_FAIL = "TOPIC_CREATE_FAIL"
export const TOPIC_CREATE_RESET = "TOPIC_CREATE_RESET"

export const QUIZ_CREATE_REQUEST = "QUIZ_CREATE_REQUEST"
export const QUIZ_CREATE_SUCCESS = "QUIZ_CREATE_SUCCESS"
export const QUIZ_CREATE_FAIL = "QUIZ_CREATE_FAIL"
export const QUIZ_CREATE_RESET = "QUIZ_CREATE_RESET"

export const TOPIC_VIEW_REQUEST = "TOPIC_VIEW_REQUEST"
export const TOPIC_VIEW_SUCCESS = "TOPIC_VIEW_SUCCESS"
export const TOPIC_VIEW_FAIL = "TOPIC_VIEW_FAIL"
export const TOPIC_VIEW_RESET = "TOPIC_VIEW_RESET"

export const TOPIC_EDIT_REQUEST = "TOPIC_EDIT_REQUEST"
export const TOPIC_EDIT_SUCCESS = "TOPIC_EDIT_SUCCESS"
export const TOPIC_EDIT_FAIL = "TOPIC_EDIT_FAIL"
export const TOPIC_EDIT_RESET = "TOPIC_EDIT_RESET"

export const TOPIC_DELETE_REQUEST = "TOPIC_DELETE_REQUEST"
export const TOPIC_DELETE_SUCCESS = "TOPIC_DELETE_SUCCESS"
export const TOPIC_DELETE_FAIL = "TOPIC_DELETE_FAIL"

export const CHECK_ENROLL_REQUEST = "CHECK_ENROLL_REQUEST"
export const CHECK_ENROLL_SUCCESS = "CHECK_ENROLL_SUCCESS"
export const CHECK_ENROLL_FAIL = "CHECK_ENROLL_FAIL"

export const COURSE_ENROLL_REQUEST = "COURSE_ENROLL_REQUEST"
export const COURSE_ENROLL_SUCCESS = "COURSE_ENROLL_SUCCESS"
export const COURSE_ENROLL_FAIL = "COURSE_ENROLL_FAIL"

export const WATCH_VIDEO_REQUEST = "WATCH_VIDEO_REQUEST"
export const WATCH_VIDEO_SUCCESS = "WATCH_VIDEO_SUCCESS"
export const WATCH_VIDEO_FAIL = "WATCH_VIDEO_FAIL"