export const COURSE_CREATE_REQUEST = "COURSE_CREATE_REQUEST"
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS"
export const COURSE_CREATE_FAIL = "COURSE_CREATE_FAIL"

export const COURSES_VIEW_REQUEST = "COURSES_VIEW_REQUEST"
export const COURSES_VIEW_SUCCESS = "COURSES_VIEW_SUCCESS"
export const COURSES_VIEW_FAIL = "COURSES_VIEW_FAIL"
export const COURSES_VIEW_RESET = "COURSES_VIEW_RESET"

export const COURSE_VIEW_REQUEST = "COURSE_VIEW_REQUEST"
export const COURSE_VIEW_SUCCESS = "COURSE_VIEW_SUCCESS"
export const COURSE_VIEW_FAIL = "COURSE_VIEW_FAIL"
export const COURSE_VIEW_RESET = "COURSE_VIEW_RESET"