export const COMMENT_CREATE_REQUEST = "COMMENT_CREATE_REQUEST"
export const COMMENT_CREATE_SUCCESS = "COMMENT_CREATE_SUCCESS"
export const COMMENT_CREATE_FAIL = "COMMENT_CREATE_FAIL"
export const COMMENT_CREATE_RESET = "COMMENT_CREATE_RESET"

export const FORUM_VIEW_REQUEST = "FORUM_VIEW_REQUEST"
export const FORUM_VIEW_SUCCESS = "FORUM_VIEW_SUCCESS"
export const FORUM_VIEW_FAIL = "FORUM_VIEW_FAIL"
export const FORUM_VIEW_RESET = "FORUM_VIEW_RESET"