export const QUIZ_CREATE_REQUEST = "QUIZ_CREATE_REQUEST"
export const QUIZ_CREATE_SUCCESS = "QUIZ_CREATE_SUCCESS"
export const QUIZ_CREATE_FAIL = "QUIZ_CREATE_FAIL"
export const QUIZ_CREATE_RESET = "QUIZ_CREATE_RESET"

export const QUIZZES_VIEW_REQUEST = "QUIZZES_VIEW_REQUEST"
export const QUIZZES_VIEW_SUCCESS = "QUIZZES_VIEW_SUCCESS"
export const QUIZZES_VIEW_FAIL = "QUIZZES_VIEW_FAIL"
export const QUIZZES_VIEW_RESET = "QUIZZES_VIEW_RESET"

export const QUIZ_VIEW_REQUEST = "QUIZ_VIEW_REQUEST"
export const QUIZ_VIEW_SUCCESS = "QUIZ_VIEW_SUCCESS"
export const QUIZ_VIEW_FAIL = "QUIZ_VIEW_FAIL"
export const QUIZ_VIEW_RESET = "QUIZ_VIEW_RESET"

export const QUIZ_QUESTION_CREATE_REQUEST = "QUIZ_QUESTION_CREATE_REQUEST"
export const QUIZ_QUESTION_CREATE_SUCCESS = "QUIZ_QUESTION_CREATE_SUCCESS"
export const QUIZ_QUESTION_CREATE_FAIL = "QUIZ_QUESTION_CREATE_FAIL"
export const QUIZ_QUESTION_CREATE_RESET = "QUIZ_QUESTION_CREATE_RESET"

export const QUIZ_QUESTION_VIEW_REQUEST = "QUIZ_QUESTION_VIEW_REQUEST"
export const QUIZ_QUESTION_VIEW_SUCCESS = "QUIZ_QUESTION_VIEW_SUCCESS"
export const QUIZ_QUESTION_VIEW_FAIL = "QUIZ_QUESTION_VIEW_FAIL"
export const QUIZ_QUESTION_VIEW_RESET = "QUIZ_QUESTION_VIEW_RESET"

export const QUIZ_QUESTION_EDIT_REQUEST = "QUIZ_QUESTION_EDIT_REQUEST"
export const QUIZ_QUESTION_EDIT_SUCCESS = "QUIZ_QUESTION_EDIT_SUCCESS"
export const QUIZ_QUESTION_EDIT_FAIL = "QUIZ_QUESTION_EDIT_FAIL"
export const QUIZ_QUESTION_EDIT_RESET = "QUIZ_QUESTION_EDIT_RESET"

export const QUIZ_QUESTION_DELETE_REQUEST = "QUIZ_QUESTION_DELETE_REQUEST"
export const QUIZ_QUESTION_DELETE_SUCCESS = "QUIZ_QUESTION_DELETE_SUCCESS"
export const QUIZ_QUESTION_DELETE_FAIL = "QUIZ_QUESTION_DELETE_FAIL"
export const QUIZ_QUESTION_DELETE_RESET = "QUIZ_QUESTION_DELETE_RESET"


export const QUIZ_SAVE_REQUEST = "QUIZ_SAVE_REQUEST"
export const QUIZ_SAVE_SUCCESS = "QUIZ_SAVE_SUCCESS"
export const QUIZ_SAVE_FAIL = "QUIZ_SAVE_FAIL"
export const QUIZ_SAVE_RESET = "QUIZ_SAVE_RESET"

export const QUIZ_EDIT_REQUEST = "QUIZ_EDIT_REQUEST"
export const QUIZ_EDIT_SUCCESS = "QUIZ_EDIT_SUCCESS"
export const QUIZ_EDIT_FAIL = "QUIZ_EDIT_FAIL"
export const QUIZ_EDIT_RESET = "QUIZ_EDIT_RESET"

export const QUIZ_DELETE_REQUEST = "QUIZ_DELETE_REQUEST"
export const QUIZ_DELETE_SUCCESS = "QUIZ_DELETE_SUCCESS"
export const QUIZ_DELETE_FAIL = "QUIZ_DELETE_FAIL"
export const QUIZ_DELETE_RESET = "QUIZ_DELETE_RESET"