export const UPLOAD_VIDEO_REQUEST = "UPLOAD_VIDEO_REQUEST"
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS"
export const UPLOAD_VIDEO_FAIL = "UPLOAD_VIDEO_FAIL"

export const DELETE_VIDEO_REQUEST = "DELETE_VIDEO_REQUEST"
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS"
export const DELETE_VIDEO_FAIL = "DELETE_VIDEO_FAIL"

export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST"
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS"
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL"

export const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST"
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS"
export const DELETE_IMAGE_FAIL = "DELETE_IMAGE_FAIL"