const DUMMY_TOPICS =  [
  {'_id': '1','topic': 'topic 1'},
  {'_id': '2','topic': 'topic 2'},
  {'_id': '3','topic': 'topic 3'},
  {'_id': '4','topic': 'topic 4'},
  {'_id': '5','topic': 'topic 5'},
]

const DUMMY_QUIZZES =  [
  {'_id': '1','title': 'quiz 1', 'done': true,},
  {'_id': '2','title': 'quiz 2', 'done': true,},
  {'_id': '3','title': 'quiz 3', 'done': false,},
  {'_id': '4','title': 'quiz 4', 'done': false,},
  {'_id': '5','title': 'quiz 5', 'done': false,},
]


export const courses = [
  {
    '_id': '1',
    'title': 'Science',
    'image': '/images/Science.jpg',
    'category': 'Form 1',
    'rating': '5',
    'numViews': '100',
    'numReviews': '20',
    'topics':DUMMY_TOPICS,
    'quiz': DUMMY_QUIZZES,
    'progress': '20',
  }, 
  {
    '_id': '2',
    'title': 'Maths',
    'image': '/images/Maths.jpg',
    'category': 'Form 1',
    'rating': '4.5',
    'numViews': '150',
    'numReviews': '30',
    'topics': DUMMY_TOPICS,
    'quiz': DUMMY_QUIZZES,
    'progress': '30',
  },
  {
    '_id': '3',
    'title': 'Chinese',
    'image': '/images/Chinese.jpg',
    'category': 'Form 1',
    'rating': '5',
    'numViews': '200',
    'numReviews': '30',
    'topics': DUMMY_TOPICS,
    'quiz': DUMMY_QUIZZES,
    'progress': '0',
  },
  {
    '_id': '4',
    'title': 'Malay',
    'image': '/images/Malay.png',
    'category': 'Form 1',
    'rating': '4',
    'numViews': '50',
    'numReviews': '30',
    'topics': DUMMY_TOPICS,
    'quiz': DUMMY_QUIZZES,
    'progress': '100',
  },
  {
    '_id': '5',
    'title': 'Science',
    'image': '/images/Science.jpg',
    'category': 'Form 2',
    'rating': '5',
    'numViews': '100',
    'numReviews': '20',
    'topics':DUMMY_TOPICS,
    'quiz': DUMMY_QUIZZES,
    'progress': '50',
  }, 
  {
    '_id': '6',
    'title': 'Maths',
    'image': '/images/Maths.jpg',
    'category': 'Form 2',
    'rating': '4.5',
    'numViews': '150',
    'numReviews': '30',
    'topics': DUMMY_TOPICS,
    'quiz': DUMMY_QUIZZES,
    'progress': '40',
  },
  {
    '_id': '7',
    'title': 'Chinese',
    'image': '/images/Chinese.jpg',
    'category': 'Form 2',
    'rating': '5',
    'numViews': '200',
    'numReviews': '30',
    'topics': DUMMY_TOPICS,
    'quiz': DUMMY_QUIZZES,
    'progress': '80',
  },
  {
    '_id': '8',
    'title': 'Malay',
    'image': '/images/Malay.png',
    'category': 'Form 2',
    'rating': '4',
    'numViews': '50',
    'numReviews': '30',
    'topics': DUMMY_TOPICS,
    'quiz': DUMMY_QUIZZES,
    'progress': '70',
  }
  
]
